//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rits.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class detail
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Gender { get; set; }
        public string DateOfBirth { get; set; }
        public string EmailID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Department { get; set; }
        public string TenthBoard { get; set; }
        public Nullable<int> TenthMarks { get; set; }
        public string TwelfthBoard { get; set; }
        public Nullable<int> TwelfthMarks { get; set; }
    
        public virtual registration registration { get; set; }
    }

    public enum Department
    {
        [Display(Name = "Computer Science")]
        ComputerScience,
        [Display(Name = "Information Science")]
        InformationScience,
        ElectronicsAndCommunication,
    }
}
